name: Deploy Firebase Config to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create firebase-config.js
        run: |
          echo "const firebaseConfig = {" > scripts/firebase-config.js
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> scripts/firebase-config.js
          echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> scripts/firebase-config.js
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> scripts/firebase-config.js
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> scripts/firebase-config.js
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> scripts/firebase-config.js
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'" >> scripts/firebase-config.js
          echo "};" >> scripts/firebase-config.js
          echo "firebase.initializeApp(firebaseConfig);" >> scripts/firebase-config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .  # Change this if you have a build folder
